language: node_js
node_js:
- node
install:
- npm i -g npm
- npm ci
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: rmyYyuvd7M1MJz6wHz7NGJMJ85k8fT5T/Ew9pxab92NYbxnwPRv+HHhfz5U89oNROdBtVneXnQAu4Z8XO7Ga29uEDci+8a9XJ9YCRdjTtOjAFwb1FjBYDm3mFQgqKpFSalXnC7528RfXEn9b2vFHAlevWXmcusjl2icxnhq4Wwy8N8xgqN3/X2iVNzf7RmhzVCe/D/uVLI1dXRurBHg7G3H4Ns3uoAM8Y1Bghl7zUpmPLbsIQDXt8J0teIRFQeQSosXjDJfWoXol7tb+VDXW59AhwKdoP9nf+dsd5p81YE+1JRC5ucAn149wbyqxlTK5W8rkxFt8dYRKqRiwQz0njOrfr/+Jml1wR+FR04Qhls6zy0X1VYuAOP27LfAuJnF3ZcBKpZWe9lnfh9qtN8h44J98qidBIHE4hlPh4e+3EhBuznGBC7X11e2qYc9VeRVYF7FN4rJTR3OnPY8bMHa70oOL1zGzc1sN1VK8SAQprigzSybEJEqrtfRpvtaUbwiB9pttm+4Y/AdSS8bTlCboegRZkI80+p1Ka9MQkAVUD28mJWL9f0L6vJRxCrbDHJJvm41S+ghSj0n4oYVsxFXHXo1VFmYnnwipw5FtOHxMS089oCzhfkWXFVwKUw/+L2jKISP48aJa5S4LiaCl0CujlhsPjVqeqa4EahhdW0/lSqE=
notifications:
  email:
  - travis@nevenall.games