language: node_js
node_js:
  - node
install:
  - npm i -g npm
  - npm ci
branches:
  only:
  - master
cache:
  directories:
    - "node_modules"
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: b0ExiwDbJ8jK5ytxwYqbj+xbd75lFSKZPfiJr2Vo6zwiNCnfXv1ngX04KOxWVIdPabs3Q0VhTUntb4qL+Zsg/g/VH1v3HOdkqMFPDjbENHE9prC8oWMekRw+N+0igA6tYYN94AfJ9HoMThguzpGLR8m6eJ4aHNUklqCgSivt+IlJmIoY6MeYgChROCh/qqujwWfoj4zwnimo49sZzXJLcaVnJ/U/7hK+t7Rmet4CqS+mImEgQu84VpYDeJJZlD3yk50UKENsa7JhsbTxIHdB+59uX5g1mQbLvCmjhc9PfihNpSjRDVp5t0j0uWyAmPYpmVjcdODw9xWAHbDnqV0hpaB6QRunPDLpsIoMG2T3piDRGUKlguxtpWxfJG2x3G3tobE+TnX6uyYCo35AGIUSB/1rB5d4rOOK/FhuDSzO9Cnm53RtoEJ2OReOfGjJ/WpdbDn/i38hRMmLMerouLN1KPQhPRPTCotnQS5mW59zM/UFXrc/m1t7jqGUd9mKs6oU8so5WShSUnYjDlx3VFnYBth72Rq17qiiQgTiiLcM7rHE0I2elDbKkk5N6vvWdMwSvNi9yb8JGXMjCRkCP3WOX8Ax8jGrkgTA22pjKU4OOAEOrEVB4VeqYPenuBhsC5V03ev7v7xhuNQVYodtwmeP1qQhxy4+yqlLuVrWpq48pBM=
notifications:
  email:
    - travis@nevenall.games
